sudo: required
language: go
go:
- '1.11'
go_import_path: github.com/xiaokangwang/AndroidLibV2ray
git:
  depth: 5
addons:
  apt:
    update: true
before_script:
- sudo ntpdate -u time.google.com
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- date
- make all
- make downloadGoMobile
script:
- go test -p 1 -tags json -v github.com/xiaokangwang/AndroidLibV2ray/...
- make BuildMobile
after_success:
deploy:
  provider: releases
  api_key:
    secure: "LyI53PY0s3xs7KJOH8DYdy2b0P6fzNgr8xSj+k/BHTL4GoNcc7UQng8iNftwpO30w8p8ok4qk2iYAHt1Qtq2GzL2FMMPtm7aEuUgHP1cDj9B9CRlVvkf6/0Af8gr/wUWb+14d/Rzz7dVhO2SVOQXKn8tBjqJYKfS8Zi1tGQpBo//ZWIrXlHYVaSjZJaGdQhBGkmAcXOB96pXQXGU55jyXsOc6DqVkFpIF/+7SX06NZEmb8x0bzLbSNG+W5gtyDGM2K/vFRD4Fh9/yF9GX/yGCTlCJm2KL/+DP51/ukz8I41J2+lJtH95/kCJdqWINq407jDDDxupmn6yGziSjWY4jFVLkU2mxvggdpOVCnnSjl6pmcftAHTWyPfTWWYb6P3h7wmI1nP+MvM9JEo50gyW2gnVnJgWr1W2fvXqMC5gKe/2M09S1XaBkndVYDIwtxBNVnvDaBmTKq6k0ipnYYlzADjotq8eyUSK7bWcnel1+YALs9mADGbxslHfu2KmkAyay5bpCmRSAE9Ag9ohCyaB8LNlHsPl5fWqRpY1zYA92KEBADX/k1+qzAR7nv8JCBIDmW9GHmfztdnGR8MkGHERDwwULM5URpnc0Pyji8E1S8Uj4RgJSRL+iJiIkD3A6phA8A25hhUZrEiR9iAVLFESgo8JsrhSv0EHGa07/XGBYJQ="
  file:
  - libv2ray.aar
  skip_cleanup: true
  on:
    tags: true
