sudo: required
language: go
go:
- '1.11'
go_import_path: github.com/xiaokangwang/AndroidLibV2ray
git:
  depth: 5
addons:
  apt:
    update: true
before_script:
- sudo ntpdate -u time.google.com
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- date
- make all
- make downloadGoMobile
script:
- go test -p 1 -tags json -v github.com/xiaokangwang/AndroidLibV2ray/...
- make BuildMobile
after_success:
deploy:
  provider: releases
  api_key:
    secure: "DJCo9XajfsTZOyDQG1fotx48gBh4+w21Jx1CxFkzS7VI8Z+MRd1wkA/t5xt31a/dR4yQv1MQM7nkOXuDiaAcDGXs8IGW6zv3UUxgyQLrlsYce8udC6Rwbb1xnPMDwe3nHBNPE0CWshoWO2GYepTY4HZkNoxqb+QOt1o2jkoIhtTaNW+vHCmDa+jyRE+nbjSUjlu2W0dOcWjHufp77f22R56U/a08czRGUF5vuxrbCnhjAM0mqn8xQ+IjT7ZMIkTqUUJ8ZMgt6DdBp8zPUzIhZGKLQ9eDMgEhyvdFxceXAxRpedeUxtx+EDWiFz2GAKyOANUhvtdrSuKmo4YGMHltlkrInr5hZmARzJAQnbTYk0uueELKJ1LXeU5byp/99nC6ZC6t5QW0QB5r5z7MBPeDL72E7vyUgbZYgQ5SXQn0jxOvAN8FIcOjO3PVV2uSLPiQhJgnFaNnY/aH6a9WVhrY6OCD46/Gq8Z8nEC6S4glMEsTC/5nfL0YN/SY1ytZDT27rT/xO4XLAAkwZ6idySESgqXl6iIQniBt4a68uGbd7oCIm9zXXcFmWQ2DyO+/N2vCB2y9PAYivsEhdBy+u7kDgXg5g+f99QO8IP5kFY1w/jcXgt04uiPB2dDuW8lB/tynx/5qa8mL07fJQu/hZmGp6tYrW0RvstlysDCMi40K+hY="
  file:
  - libv2ray.aar
  skip_cleanup: true
  on:
    tags: true
